"""Empirically-derived runtime limit models.

Auto-generated by scripts/analyze_thresholds.py from
results/benchmark_results.csv. Do not edit by hand; re-run the analysis
script instead if the benchmark data changes.
"""

import math

TIME_LIMIT_SECONDS = 200.0

# --- Brute Force (C++) model ---
# Predicted runtime (seconds) ~= BRUTE_FORCE_RATE * C(removable, k) * edges
BRUTE_FORCE_RATE = 5.0960772233572745e-08

# --- Important Separators (C++) model ---
# Predicted runtime (seconds) ~= IMPORTANT_SEPARATORS_SAFETY_MARGIN *
#     IMPORTANT_SEPARATORS_A * edges * IMPORTANT_SEPARATORS_B ** k
IMPORTANT_SEPARATORS_A = 4.62153777840372e-06
IMPORTANT_SEPARATORS_B = 2.1557683151968843
IMPORTANT_SEPARATORS_SAFETY_MARGIN = 21.381340468906867


def predict_brute_force_seconds(removable: int, k: int, edges: int) -> float:
    """Predicts the Brute Force (C++) runtime in seconds."""
    if k < 0 or k > removable or edges <= 0:
        return 0.0
    combos = math.comb(removable, k)
    return BRUTE_FORCE_RATE * combos * edges


def predict_important_separators_seconds(k: int, edges: int) -> float:
    """Predicts the Important Separators (C++) runtime in seconds."""
    if k < 0 or edges <= 0:
        return 0.0
    return (
        IMPORTANT_SEPARATORS_SAFETY_MARGIN
        * IMPORTANT_SEPARATORS_A
        * edges
        * (IMPORTANT_SEPARATORS_B ** k)
    )
