"""Empirically-measured per-map k limits.

Auto-generated by scripts/find_max_k.py. Do not edit by hand; re-run the
discovery script instead if the benchmark hardware or datasets change.

For each (algorithm, map) pair, scripts/find_max_k.py ran the algorithm
once at k=1, 2, 3, ... (increasing) and timed each run with a real
stopwatch, stopping as soon as a run exceeded 210 seconds or
failed. MAX_K_TABLE records the largest k that finished within that
budget, keyed by a structural signature of the graph (nodes, edges,
removable node count) since a Graph object doesn't carry its source
filename.
"""

TIME_LIMIT_SECONDS = 210.0

# {algorithm_name: {(nodes, edges, removable): max_k}}
MAX_K_TABLE = {'Brute Force (C++)': {(109, 472, 95): 4, (243, 788, 241): 3, (112, 322, 107): 4, (224, 816, 222): 3, (93, 294, 87): 4}, 'Important Separators (C++)': {(109, 472, 95): 15, (243, 788, 241): 11, (112, 322, 107): 15, (224, 816, 222): 11, (93, 294, 87): 15}, 'MILP (OR-Tools)': {(109, 472, 95): 15, (243, 788, 241): 15, (112, 322, 107): 15, (224, 816, 222): 15, (93, 294, 87): 15}}


def get_max_k(algorithm_name: str, nodes: int, edges: int, removable: int):
    """Looks up the empirically-measured max k for a graph matching the
    given structural signature.

    Returns:
        The largest k known to finish within TIME_LIMIT_SECONDS for this
        (algorithm, graph shape), or None if this graph shape was not
        part of the measured datasets (in which case no limit should be
        enforced).
    """
    per_algo = MAX_K_TABLE.get(algorithm_name)
    if not per_algo:
        return None
    return per_algo.get((nodes, edges, removable))
