import math as math
from pathlib import Path

# Size test grid: dense coverage at the low end (10x10..20x20), then
# coarser steps (25..50, 75..200), then increments of 100 up to 1000x1000.
TEST_SIZES = sizes = (
    list(range(10, 21))
    + [25, 30, 35, 40, 45, 50]
    + [75, 100, 125, 150, 200, 300, 400, 500, 600, 700, 800, 900, 1000]
)

""" 
Listing of levels and their parameters. 
Key is the level's string file name.
Value is a list of known parameters for the level, like (7, 34) meaning k=7 gives expected value 34.
"""
LEVELS = {
  "horse_arcs_170": [(12, 125)],
  "horse_diamonds_126":[(2,1),(7,39)],
  "horse_dots":[(8,11)],
  "horse_u-turn_128":[(8,41)],
  "horse_portals_cherries": [(8, 32)],
}

"""
Display metadata for the real (hand-authored) map files in data/*.txt.

This intentionally excludes the synthetic size_test_* graphs generated by
generate_size_test(), since those are plotted with the graph size (N) on
one of the axes already and do not need a separate title/metadata entry.

Each entry is keyed by the map's file name (as used when loading it, e.g.
via load_graph_from_map) and holds:
  - title: A short, human-friendly display name to use in place of the raw
    file name when titling result graphs.
  - n_nodes: Total number of nodes in the loaded graph (including the
    synthetic 't' sink node added by the map loader).
  - m_edges: Total number of undirected edges in the loaded graph.
  - min_k: The minimum number of nodes that must be removed to disconnect
    s from t (i.e. the size of a minimum s-t vertex separator).

These values are derived from the map files themselves and can be
recomputed/verified at any time by running this module directly:
    python data/generate.py
"""
MAP_METADATA = {
    "horse_arcs_170.txt": {
        "title": "Day 170: Arcs",
        "n_nodes": 243,
        "m_edges": 394,
        "min_k": 1,
    },
    "horse_diamonds_126.txt": {
        "title": "Day 126: Diamonds",
        "n_nodes": 112,
        "m_edges": 161,
        "min_k": 2,
    },
    "horse_dots.txt": {
        "title": "Day 120: Dots",
        "n_nodes": 224,
        "m_edges": 408,
        "min_k": 3,
    },
    "horse_u-turn_128.txt": {
        "title": "Day 128: U-Turn",
        "n_nodes": 93,
        "m_edges": 147,
        "min_k": 3,
    },
    "dry-portals.txt": {
        "title": "Day 247: Dry Portals",
        "n_nodes": 109,
        "m_edges": 236,
        "min_k": 4,
    },
}


def map_display_title(dataset_name: str) -> str:
    """Returns a display title with metadata for a dataset name.

    Looks up `dataset_name` (e.g. "horse_dots.txt") in MAP_METADATA and
    returns a string like "Dots (n=224, m=408, min k=3)". If the dataset
    is not found in MAP_METADATA (e.g. it is a generated size_test graph,
    or an unknown file), the raw dataset_name is returned unchanged.

    Args:
        dataset_name: The map's file name, as recorded in the results CSV
            'Dataset' column (e.g. "horse_dots.txt").

    Returns:
        A human-friendly title string, or dataset_name if no metadata is
        available for it.
    """
    meta = MAP_METADATA.get(dataset_name)
    if meta is None:
        return dataset_name
    return (
        f"{meta['title']} (n={meta['n_nodes']}, m={meta['m_edges']}, "
        f"min k={meta['min_k']})"
    )


# pattern like this where k=8 gives best score:
# - ### ###
# -        
# - ### ###
# -        
# - ### ###
# -        
# - ### ###


def generate_size_test(size):
  mid = size // 2
  cols = [mid, mid + 2, mid - 2]
  rows = [mid]
  level_map = [["#" for _ in range(size)] for _ in range(size)]
  for i in range(size):
    for j in range(size):
      # clear the entire column or row marked for clearing
      if i in rows or j in cols:
        level_map[i][j] = " "
  # add horse
  level_map[mid][mid] = "H"
  
  # convert to list of strings
  level_map = ["".join(row) for row in level_map]
  return level_map


def _compute_map_metadata() -> dict:
    """Recomputes MAP_METADATA's n_nodes/m_edges/min_k values from the
    actual map files in the data directory, by loading each graph and
    running a minimum s-t separator computation.

    This is used by the `python data/generate.py` self-check below to
    verify that MAP_METADATA stays in sync with the map files; it is not
    used at benchmark/visualisation runtime (MAP_METADATA is a static
    dict so results stay stable and fast to import).

    Returns:
        A dict keyed by map file name with freshly computed
        {"n_nodes", "m_edges", "min_k"} values.
    """
    import sys

    repo_root = Path(__file__).resolve().parent.parent
    sys.path.insert(0, str(repo_root / "src"))

    from horse_algos.tools.map_loader import load_graph_from_map
    from horse_algos.graph import minSeparator

    computed = {}
    for filename in MAP_METADATA:
        graph, s, t = load_graph_from_map(filename)
        n_nodes = len(graph.nodeValues)
        m_edges = sum(len(adj) for adj in graph.adjList) // 2
        min_k = len(minSeparator(graph, s, t))
        computed[filename] = {
            "n_nodes": n_nodes,
            "m_edges": m_edges,
            "min_k": min_k,
        }
    return computed


if __name__ == "__main__":
    # Recompute the graph metadata directly from the map files and report
    # any mismatch against the static MAP_METADATA table above, so the
    # table can be manually verified/updated after editing a map file.
    computed = _compute_map_metadata()
    mismatches = []
    for filename, meta in MAP_METADATA.items():
        fresh = computed[filename]
        for key in ("n_nodes", "m_edges", "min_k"):
            if meta[key] != fresh[key]:
                mismatches.append((filename, key, meta[key], fresh[key]))
        print(
            f"{filename}: title={meta['title']!r} n_nodes={fresh['n_nodes']} "
            f"m_edges={fresh['m_edges']} min_k={fresh['min_k']}"
        )

    if mismatches:
        print("\nMismatches between MAP_METADATA and freshly computed values:")
        for filename, key, old, new in mismatches:
            print(f"  {filename}: {key} recorded={old} computed={new}")
    else:
        print("\nMAP_METADATA is up to date with the current map files.")
