"""Analyze results/benchmark_results.csv to derive empirical runtime models
for each algorithm and compute the input thresholds (in terms of nodes,
edges and k) beyond which an algorithm is expected to take longer than
TIME_LIMIT_SECONDS (200s) to run.

Run with:  python scripts/analyze_thresholds.py
"""

import csv
import math
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))
sys.path.insert(0, str(REPO_ROOT))

from horse_algos.tools.map_loader import load_graph_from_map  # noqa: E402

TIME_LIMIT_SECONDS = 200.0
CSV_PATH = REPO_ROOT / "results" / "benchmark_results.csv"
OUTPUT_PATH = REPO_ROOT / "src" / "horse_algos" / "algorithms" / "runtime_limits.py"

BRUTE_FORCE_NAME = "Brute Force (C++)"
IMPORTANT_SEPARATORS_NAME = "Important Separators (C++)"
MILP_NAME = "MILP (OR-Tools)"

RUNTIME_LIMITS_TEMPLATE = '''"""Empirically-derived runtime limit models.

Auto-generated by scripts/analyze_thresholds.py from
results/benchmark_results.csv. Do not edit by hand; re-run the analysis
script instead if the benchmark data changes.
"""

import math

TIME_LIMIT_SECONDS = {time_limit}

# --- Brute Force (C++) model ---
# Predicted runtime (seconds) ~= BRUTE_FORCE_RATE * C(removable, k) * edges
BRUTE_FORCE_RATE = {bf_rate}

# --- Important Separators (C++) model ---
# Predicted runtime (seconds) ~= IMPORTANT_SEPARATORS_SAFETY_MARGIN *
#     IMPORTANT_SEPARATORS_A * edges * IMPORTANT_SEPARATORS_B ** k
IMPORTANT_SEPARATORS_A = {is_a}
IMPORTANT_SEPARATORS_B = {is_b}
IMPORTANT_SEPARATORS_SAFETY_MARGIN = {is_margin}


def predict_brute_force_seconds(removable: int, k: int, edges: int) -> float:
    """Predicts the Brute Force (C++) runtime in seconds."""
    if k < 0 or k > removable or edges <= 0:
        return 0.0
    combos = math.comb(removable, k)
    return BRUTE_FORCE_RATE * combos * edges


def predict_important_separators_seconds(k: int, edges: int) -> float:
    """Predicts the Important Separators (C++) runtime in seconds."""
    if k < 0 or edges <= 0:
        return 0.0
    return (
        IMPORTANT_SEPARATORS_SAFETY_MARGIN
        * IMPORTANT_SEPARATORS_A
        * edges
        * (IMPORTANT_SEPARATORS_B ** k)
    )
'''


def load_dataset_stats():
    """Returns {dataset_filename: (nodes, edges, removable)} for every
    dataset file found in the data/ directory."""
    data_dir = REPO_ROOT / "data"
    stats = {}
    for path in sorted(data_dir.glob("*.txt")):
        graph, s, t = load_graph_from_map(path.name)
        nodes = len(graph.nodeValues)
        edges = sum(len(adj) for adj in graph.adjList)
        removable = len([
            i for i in range(nodes)
            if i not in graph.infSet and i != s and i != t
        ])
        stats[path.name] = (nodes, edges, removable)
    return stats


def load_rows():
    """Loads and de-duplicates rows from the benchmark CSV.

    Returns a list of dicts: algorithm, dataset, k, median, is_error.
    """
    rows = []
    seen = set()
    with open(CSV_PATH, newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        next(reader)  # header
        for r in reader:
            if len(r) < 11:
                continue
            algo, dataset, k_str, median_str = r[0], r[1], r[2], r[3]
            result_str = r[10]
            key = (algo, dataset, k_str, result_str)
            if key in seen:
                continue
            seen.add(key)
            try:
                median = float(median_str)
            except ValueError:
                median = 0.0
            is_error = result_str.startswith("ERROR")
            rows.append({
                "algorithm": algo,
                "dataset": dataset,
                "k": int(k_str),
                "median": median,
                "is_error": is_error,
            })
    return rows


def fit_brute_force_model(rows, dataset_stats):
    """Fits T ~= rate * C(removable, k) * edges using the worst observed
    (max) ratio across all valid (non-error) runs, so the resulting model
    is a conservative (upper-bound) predictor of the runtime.
    """
    max_rate = 0.0
    samples = []
    for r in rows:
        if r["algorithm"] != BRUTE_FORCE_NAME or r["is_error"] or r["median"] <= 0:
            continue
        _, edges, removable = dataset_stats[r["dataset"]]
        if r["k"] > removable:
            continue
        combos = math.comb(removable, r["k"])
        if combos == 0 or edges == 0:
            continue
        rate = r["median"] / (combos * edges)
        samples.append((r["dataset"], r["k"], combos, edges, r["median"], rate))
        max_rate = max(max_rate, rate)
    return max_rate, samples


def fit_important_separators_model(rows, dataset_stats):
    """Fits T ~= a * edges * b^k via log-linear least squares:
        log(T / edges) = log(a) + k * log(b)
    using all valid (non-error) runs across all datasets, then reports the
    fitted (a, b) alongside a safety margin (largest positive residual
    multiplier) so callers can conservatively avoid underestimating.
    """
    xs, ys, samples = [], [], []
    for r in rows:
        if r["algorithm"] != IMPORTANT_SEPARATORS_NAME or r["is_error"] or r["median"] <= 0:
            continue
        _, edges, _ = dataset_stats[r["dataset"]]
        if edges == 0:
            continue
        y = math.log(r["median"] / edges)
        xs.append(r["k"])
        ys.append(y)
        samples.append((r["dataset"], r["k"], edges, r["median"]))

    n = len(xs)
    if n < 2:
        raise RuntimeError("Not enough Important Separators (C++) data to fit a model.")

    mean_x = sum(xs) / n
    mean_y = sum(ys) / n
    cov_xy = sum((x - mean_x) * (y - mean_y) for x, y in zip(xs, ys))
    var_x = sum((x - mean_x) ** 2 for x in xs)
    slope = cov_xy / var_x  # = log(b)
    intercept = mean_y - slope * mean_x  # = log(a)

    b = math.exp(slope)
    a = math.exp(intercept)

    max_ratio = 1.0
    for (dataset, k, edges, median), y in zip(samples, ys):
        predicted = math.exp(intercept + slope * k)
        actual = math.exp(y)
        if predicted > 0:
            max_ratio = max(max_ratio, actual / predicted)

    return a, b, max_ratio, samples


def fit_milp_summary(rows):
    """Reports the worst observed MILP runtime; MILP has not been observed
    to exceed the time limit in the available benchmark data, so no
    rejection model is derived for it.
    """
    worst = None
    for r in rows:
        if r["algorithm"] != MILP_NAME or r["is_error"]:
            continue
        if worst is None or r["median"] > worst[0]:
            worst = (r["median"], r["dataset"], r["k"])
    return worst


def write_runtime_limits_module(bf_rate, is_a, is_b, is_margin):
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(RUNTIME_LIMITS_TEMPLATE.format(
            time_limit=TIME_LIMIT_SECONDS,
            bf_rate=repr(bf_rate),
            is_a=repr(is_a),
            is_b=repr(is_b),
            is_margin=repr(is_margin),
        ))


def main():
    dataset_stats = load_dataset_stats()
    rows = load_rows()

    bf_rate, bf_samples = fit_brute_force_model(rows, dataset_stats)
    is_a, is_b, is_margin, is_samples = fit_important_separators_model(rows, dataset_stats)
    milp_worst = fit_milp_summary(rows)

    print("=== Dataset structural stats ===")
    for name, (nodes, edges, removable) in dataset_stats.items():
        print(f"  {name:25s} nodes={nodes:5d} edges={edges:5d} removable={removable:5d}")

    print(f"\n=== {BRUTE_FORCE_NAME} model: T ~= rate * C(removable, k) * edges ===")
    print(f"  fitted rate (conservative max) = {bf_rate:.6e} s per (combination * edge)")
    print(f"  based on {len(bf_samples)} samples")
    for name, (nodes, edges, removable) in dataset_stats.items():
        if edges == 0 or bf_rate == 0:
            continue
        max_combos = TIME_LIMIT_SECONDS / (bf_rate * edges)
        print(f"  {name:25s} max combinations for <{TIME_LIMIT_SECONDS:.0f}s = {max_combos:,.0f}")

    print(f"\n=== {IMPORTANT_SEPARATORS_NAME} model: T ~= a * edges * b^k ===")
    print(f"  fitted a = {is_a:.6e}, b = {is_b:.4f}, safety margin = {is_margin:.4f}")
    for name, (nodes, edges, removable) in dataset_stats.items():
        if edges == 0:
            continue
        rhs = TIME_LIMIT_SECONDS / (is_margin * is_a * edges)
        if rhs <= 0 or is_b <= 1:
            continue
        max_k = math.log(rhs) / math.log(is_b)
        print(f"  {name:25s} max k for <{TIME_LIMIT_SECONDS:.0f}s = {max_k:.2f}")

    print(f"\n=== {MILP_NAME} ===")
    if milp_worst:
        print(f"  worst observed median runtime = {milp_worst[0]:.3f}s "
              f"(dataset={milp_worst[1]}, k={milp_worst[2]})")
        print("  No MILP run in the benchmark data exceeds the time limit; "
              "no rejection model derived.")

    write_runtime_limits_module(bf_rate, is_a, is_b, is_margin)
    print(f"\nWrote fitted runtime model to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
